### ISSUE TITLE
transaction hash error

### ISSUE THREAD

**Issue by YuryYa** [yashmadhwal/merkle_patricia_tree_concept#2]
The function 

>> def generate_transaction_hash():
>>      ms = time.time()
>>     return get_hash(str(ms), simple_hash=False)

is strange. It generates wrong hashes in

>> def generate_users

and

>> def generate_transaction

please, fix generate_users and generate_transaction

**Comment by yashmadhwal** [comment]
Resolved at commit: 421fccdb77f11df99e1be32f95df580b7b55f708
