### ISSUE TITLE
Generate random users in GetBalanceExample

### ISSUE THREAD

**Issue by YuryYa** [yashmadhwal/merkle_patricia_tree_concept#5]
We need random users instead of hashlib.sha224(bytes(i)).hexdigest().

Generate a random reproducible array with user ids.

Changes around
https://github.com/yashmadhwal/merkle_patricia_tree_concept/blob/ce71af2a937e4f1082188ebac3f9dc8561f811b1/Without%20database/GetBalanceExample.py#L17
and
https://github.com/yashmadhwal/merkle_patricia_tree_concept/blob/ce71af2a937e4f1082188ebac3f9dc8561f811b1/Without%20database/GetBalanceExample.py#L25 are needed

**Comment by yashmadhwal** [comment]
For simplicity.
We are using dictionary for users. 
`user = {
'user_0': #hash224(int(0)),
'user_1': #hash224(int(1)),
..., 'user_n-1': #hash224(int(n-1))}`

Making easy to create transaction for dictionary of users.
